# Generated by Django 4.2.16 on 2025-04-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfquote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('11', '11 Irons All Types'), ('10', '10 Irons All Types'), ('9', '9 Irons All Types'), ('8', '8 Irons All Types'), ('7', '7 Irons All Types'), ('6', '6 Irons All Types'), ('5', '5 Irons All Types')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='makeups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='golfquote.makeup'),
        ),
    ]
